version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.18
    working_directory: /home/circleci/project/frontend
    steps:
      - checkout
      - run:
          name: Find Working directory name
          command: pwd && ls
      - run:
          name: Install deps
          command: yarn install
      - run:
          name: Run tests
          command: yarn test

workflows:
  build-and-test:
    jobs:
      - build-and-test